# Generated by Django 5.2.3 on 2025-07-01 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_student_user_student_courses'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Marks',
            new_name='Mark',
        ),
        migrations.RenameField(
            model_name='mark',
            old_name='marks',
            new_name='marks_obtained',
        ),
        migrations.AlterField(
            model_name='attendance',
            name='status',
            field=models.BooleanField(),
        ),
    ]
