# Generated by Django 5.2.3 on 2025-07-01 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_student_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mark',
            old_name='marks_obtained',
            new_name='marks',
        ),
    ]
