# Generated by Django 5.2.3 on 2025-07-02 09:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_department_rename_is_approved_teacher_approved_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='name',
            field=models.CharField(default='unknown', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='teacher',
            name='contact',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.department'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='dob',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='skills',
            field=models.TextField(blank=True, null=True),
        ),
    ]
