# Generated by Django 5.2.3 on 2025-07-03 06:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_course_department'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='department',
        ),
    ]
